{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale-chart.name" . }}-cm
data:
  config.yaml: |-
    {{- .Values.configmap.configuration | nindent 4}}
{{- end -}}