apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale-chart.name" . }}-svc
  labels:
    {{- include "headscale-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: 8080
      protocol: TCP
      name: server
    - port: {{ .Values.service.metrics.port }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "headscale-chart.selectorLabels" . | nindent 4 }}
